### PR TITLE
fix: limit max height and add autoscroll for dropdown list

### PR DESCRIPTION
**Pull request by cschockaert**
This is a quick and dirty fix to resolve too long dropdown list referenced in this issue:

https://github.com/gentics/mesh/issues/218

### CODE REVIEW

**Comment by philippguertler** [comment]
Would it work for you if we instead of your changes just added these two rules to the `.contents` class?
```
    max-height: 450px;
    overflow: auto;
```
This would change the look from this
screenshot_20180925_115733

to this:

screenshot_20180925_115634

**Comment by cschockaert** [comment]
@philippguertler you are rigth, just tested that solution on local and it worked like a charm
thanks, i updated this PR

**Comment by philippguertler** [comment]
Great! Glad it worked for you. The fix will be included in the next release of Mesh.

**Comment by philippguertler** [comment]
@cschockaert The fix is now released and available in Mesh 0.24.1

**Comment by philippguertler** [comment]
Fixes #46

**Pull request merged**
